name: Zy Pipeline

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build message
        run: echo "Hello from GitHub Actions!"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "Hello from GitHub Actions!"

  matrix_Jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print this message
        run: echo "Hello from the matrix job"

